name: Publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1
      - name: Install dependencies
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.com/
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1
      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get git head
        run: echo "GIT_HEAD=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Gen npmrc
        run: echo "//registry.npmjs.com/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> ./.npmrc
      - name: Build&publish
        run: sh ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          TAG_VERSION: ${{env.TAG_VERSION}}
          GIT_HEAD: ${{env.GIT_HEAD}}
          REGISTRY: https://registry.npmjs.com/

  publish-docs:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1

      - name: Install dependencies
        run: pnpm i

      - name: Fetch Crowdin token for pulling languages
        run: pnpm docs:crowdin
        env:
          CROWDIN_TOKEN: ${{secrets.CROWDIN_TOKEN}}

      - name: Pull Crowdin translations
        run: cd docs && pnpm exec crowdin download

      - name: Generate common locale
        run: pnpm docs:gen-locale

      - name: Install latest Element Plus
        run: cd docs && pnpm i element-plus@latest

      - name: Build website
        run: pnpm docs:build
        env:
          DOC_ENV: production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
          GIT_CONFIG_NAME: ElementPlusBot
          GIT_CONFIG_EMAIL: hello@element-plus.org
          COMMIT_MESSAGE: website deploy

      - name: Sync
        env:
          TRIGGERSYNCURL: ${{ secrets.TRIGGERSYNCURL }}
        run: curl "$TRIGGERSYNCURL"
